spring.application.name=Job Portal

# Database Configuration (Pre-configured for Neon PostgreSQL Direct Endpoint, supports Environment Variables override)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-frosty-mountain-appb6wvy.c-7.us-east-1.aws.neon.tech/jobportal?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_W3dyGB7CYRbV}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}

# HikariCP Pool Configuration for Neon
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Server Configuration
server.tomcat.max-part-count=50